name : Basic workflow

on : [push]
jobs:
   run-python:
     runs-on : ubuntu-latest

     steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Python Script
          run: python3 app.py

        - name: Print message
          run: echo "Workflow executed successfully!"

        - name: Present Working Directory
          run: pwd

        - name: List all files
          run: ls -a
