name: Workflow 1 Basic

on:
  push:
    branches:
      - slack-notify/6377

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Say Hello
        run: echo "Hello, CI/CD started!"
      - name: Step 2 - Show branch
        run: |
          echo " Branch: $GITHUB_REF "
      - name: Step 3 - Show files
        run: ls -la        
